#!/bin/sh

if ! echo $1 | grep "out-[0-9][0-9][0-9]-[0-9][0-9]-2"> /dev/null; then
	exit 1
fi

R=`echo $1 | sed 's/out-//' | sed 's/-.*//'`
L=`echo $1 | sed 's/out-...-//' | sed 's/-2//'`

if [ -z $R ]; then
	exit 1
fi
if [ -z $L ]; then
	exit 1
fi

N=80

CALL="osl -N$N -S0 -L$L -R$R -K0.2:0.49:30 -T0:0.99:100 -k"
#echo $CALL

out=`$CALL`
#echo $out
echo $out > out-$R-$L-0

k=`echo $out | awk '{print $2}'`
t=`echo $out | awk '{print $3}'`

K=`echo $k | awk '{print $1-0.008":"$1+0.008":9"}'`
T=`echo $t | awk '{print $1-0.008":"$1+0.008":9"}'`

CALL="osl -N$N -S0 -L$L -R$R -K$K -T$T -k"
#echo $CALL

out=`$CALL`
#echo $out
echo $out > out-$R-$L-1

k=`echo $out | awk '{print $2}'`
t=`echo $out | awk '{print $3}'`

K=`echo $k | awk '{print $1-0.0016":"$1+0.0016":9"}'`
T=`echo $t | awk '{print $1-0.0016":"$1+0.0016":9"}'`

CALL="osl -N$N -S0 -L$L -R$R -K$K -T$T -k"
#echo $CALL

out=`$CALL`
#echo $out
echo $out > out-$R-$L-2

