void Jn(double v, double zr, double zi, double *yr, double *yi);
void Jn_exp(double v, double zr, double zi, double *yr, double *yi);
void J0(double zr, double zi, double *yr, double *yi);
void J1(double zr, double zi, double *yr, double *yi);
void Yn(double v, double zr, double zi, double *yr, double *yi);
void Yn_exp(double v, double zr, double zi, double *yr, double *yi);
void Hn1(double v, double zr, double zi, double *yr, double *yi);
void Hn2(double v, double zr, double zi, double *yr, double *yi);
void Hn1_exp(double v, double zr, double zi, double *yr, double *yi);
void Hn2_exp(double v, double zr, double zi, double *yr, double *yi);
void In(double v, double zr, double zi, double *yr, double *yi);
void In_exp(double v, double zr, double zi, double *yr, double *yi);
void Kn(double v, double zr, double zi, double *yr, double *yi);
void Kn_exp(double v, double zr, double zi, double *yr, double *yi);
void Ai(double zr, double zi, double *yr, double *yi);
void Ai1(double zr, double zi, double *yr, double *yi);
void Bi(double zr, double zi, double *yr, double *yi);
void Bi1(double zr, double zi, double *yr, double *yi);
void Ai_exp(double zr, double zi, double *yr, double *yi);
void Ai1_exp(double zr, double zi, double *yr, double *yi);
void Bi_exp(double zr, double zi, double *yr, double *yi);
void Bi1_exp(double zr, double zi, double *yr, double *yi);
void Log(double zr, double zi, double *yr, double *yi);
